# /!\ travis-ci does not have a fortran build config
# we will use a solution based on
# https://github.com/ScottWales/fortran-build-testing/blob/master/.travis.yml

language: c

env:
    global:
        - FC=gfortran
        - OMPI_FC=${FC}

install:
    - sudo apt-get update
    - sudo apt-get install gfortran openmpi-bin libopenmpi-dev

cache:
  paths:
  untracked: false

before_script:
  - export AMRVAC_DIR=$(pwd)
  - export ARCH=default
  - export NUM_PROCS=2          # we have 2 cores
  - cd $AMRVAC_DIR/src
  - ./update_dependencies.sh --verbose || exit 1
  - cd $AMRVAC_DIR/lib
  - make clean
  - make -j || exit 1
  - cd $AMRVAC_DIR/tests

jobs:
    include:
    - script: bash test_runner.sh hd
    - script: bash test_runner.sh mhd
    - script: bash test_runner.sh rho
    - script: bash test_runner.sh mg
    - script: bash test_runner.sh rd
    # not set up yet (missing a makefile in tests/particles/ and in tests/nonlinear/)
    #- script: bash test_runner.sh nonlinear
    #- script: bash test_runner.sh particle
