############################################################
## submit description file for
## static build of MPI under the vanilla universe
############################################################
universe = vanilla
getenv = true
executable = /users/chi-kit.cheong/.conda/envs/gmunu_env/bin/mpirun
request_cpus = 32
arguments = -np 32 gmunu -i para.par
#should_transfer_files = yes
#when_to_transfer_output = on_exit
#transfer_input_files = my_mpi_linked_executable
request_memory = 32000MB
log = logfile.log
output = outfile
error = errfile
queue

