############################################################
## submit description file for
## static build of MPI under the vanilla universe
############################################################
universe = vanilla
getenv = true
executable = /users/chi-kit.cheong/local/mpich-3.3.2/bin/mpirun
request_cpus = NP
arguments = -np NP ./gmunu -i PARA
#should_transfer_files = yes
#when_to_transfer_output = on_exit
#transfer_input_files = my_mpi_linked_executable
request_memory = NP000MB
log = logfile.log
output = outfile
error = errfile
queue

